### ISSUE TITLE
pandoc.exe: Error running filter .\examples\caps.py

### ISSUE THREAD

**Issue by kexxxfeng** [jgm/pandocfilters#53]
Hello,Sir.
Thx for your project very much. 

I'm interested in Markdown. So, I found `pandoc` is something I wanted. But It couldn't parse `* [] task1` to `<p><input type="checkbox"/>task1</p>`. Then, I decided to write a filter to resolve it. 

Then 
* I installed Python 3.5.
* Clone your project to test the filters
* I opened `Powershell` on Windows 10 as administrator
* Go to the director of the project
* Run `Python step.py install`
* Run `pandoc --filter ./examples/caps.py`

But there was an error after I had run `pandoc --filter ./examples/caps.py`. 
The error is 
```
PS C:\Users\MyName\Downloads\pandoc-filter\pandocfilters-master\examples> pandoc --filter .\caps.py
abcd
^Z
pandoc.exe: Error running filter .\caps.py
C:\Users\MyName\Downloads\pandoc-filter\pandocfilters-master\examples\caps.py: createProcess: invalid argument (Exec format error)
PS C:\Users\MyName\Downloads\pandoc-filter\pandocfilters-master\examples>
```
And then, I checked my way again and again, it was still the same.
So, I asked google, but nobody had this error.

In the end, I ask you for help. Was anything forgot to write in the `readme`?

**Comment by jgm** [comment]
What version of pandoc?
And, do you get the same error if you leave off the .\
before caps.py?

+++ Feng [Dec 21 16 01:57 ]:

**Comment by kexxxfeng** [comment]
Pandoc version: 1.17.2

Yes, it's the same in that occasion.

**Comment by sergiocorreia** [comment]
Try the latest Pandoc (1.9). Had the same error and with 1.8 and 1.9 it's gone

**Comment by ickc** [comment]
> Try the latest Pandoc (1.9). Had the same error and with 1.8 and 1.9 it's gone

@kexxxfeng, he means 1.18 and 1.19. Anyway, it is always a good idea to use the latest versions of everything (in this case, pandocfilter and pandoc). Often bugs are already fixed in the latest version.

And also you might check out @sergiocorreia's alternative of pandocfilters — [panflute](https://github.com/sergiocorreia/panflute). `@jgm` recommended this, and @sergiocorreia has ported the examples, including the [caps.py](https://github.com/sergiocorreia/panflute/blob/master/examples/panflute/caps.py) you were trying.

And regarding your need to use GitHub checkbox, you might also want to see jgm/pandoc#3051, especially [this comment by `@jgm`](https://github.com/jgm/pandoc/issues/3051#issuecomment-267002299). He already made an example on what syntax to use (basically a span enclosing the checked/unchecked item). But note that the discussion over there isn't finalized.
